POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title":  "Blog post title",
  "author": "me",
  "url": "google.com",
  "likes":  100500,
  "userId": "6204fcf81176aba0663449cd"
}

###
